name: sidecar_analyzer_plugin_core
description: A starting point for Dart libraries or applications.
version: 0.1.11-dev.8
publish_to: https://dart.cloudsmith.io/fine-designs/sidecar_analyzer_plugin_core/
repository: https://github.com/pattobrien/sidecar/

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  analyzer_plugin: ^0.11.1
  cli_util: ^0.3.5
  collection: ^1.16.0
  glob: ^2.1.0
  hotreloader: ^3.0.5
  meta: ^1.7.0
  path: ^1.8.1
  riverpod: ^1.0.3+1
  sidecar:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar/
    version: ^0.1.11-dev.4
  source_span: ^1.8.0
  uuid: ^3.0.6
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
