name: sidecar_analyzer_plugin_core
description: A starting point for Dart libraries or applications.
version: 0.1.17-dev.10
publish_to: https://dart.cloudsmith.io/fine-designs/sidecar_analyzer_plugin_core/
repository: https://github.com/pattobrien/sidecar/

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  analyzer_plugin: ^0.11.1
  characters: ^1.2.0
  cli_util: ^0.3.5
  collection: ^1.16.0
  freezed_annotation: ^2.1.0
  glob: ^2.1.0
  hotreloader: ^3.0.5
  meta: ^1.7.0
  path: ^1.8.1
  riverpod: ^2.0.0-dev.9
  rxdart: ^0.27.5
  sidecar:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar/
    version: ^0.1.17-dev.10
  sidecar_annotations:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar_annotations/
    version: ^0.1.17-dev.1
  source_span: ^1.8.0
  uuid: ^3.0.6
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.1.0
  lints: ^2.0.0
  test: ^1.16.0
