name: sidecar_annotations
description: Annotations to guide sidecar lint and edit rules.
version: 0.1.0-dev.1
repository: https://github.com/pattobrien/sidecar/
homepage: https://github.com/pattobrien/sidecar/

environment:
  sdk: ">=2.12.0 <3.0.0"
