name: sidecar_lints
description: A starting point for Dart libraries or applications.
version: 0.1.6
publish_to: https://micropub-3qduh.ondigitalocean.app/
repository: https://github.com/pattobrien/sidecar/tree/master/repositories/sidecar_lints/

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  analyzer_plugin: ^0.11.1
  collection: ^1.16.0
  path: ^1.8.0
  sidecar:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar/
    version: ^0.1.10

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

micropub: sidecar

sidecar:
  edits:
    output_ast_node_tree:
      class: OutputAstNodeTree
      import: sidecar_lints/sidecar_lints.dart
