name: sidecar_lints
description: A starting point for Dart libraries or applications.
version: 0.1.0-dev.1
repository: https://github.com/pattobrien/sidecar/tree/master/repositories/sidecar_lints/

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  analyzer_plugin: ^0.11.1
  collection: ^1.16.0
  path: ^1.8.0
  sidecar: ^0.1.0-dev.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

micropub: sidecar

sidecar:
  assists:
    - output_ast_node_tree
    - output_source_span
