name: data_rules
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ^5.0.0
  path: ^1.8.0
  sidecar:
    path: ../../packages/sidecar/

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

sidecar:
  lints:
    - some_data_rule
    - some_lint_rule
  assists:
    - some_assist_rule
