name: flutter_utilities
description: A starting point for Dart libraries or applications.
version: 0.1.12
# publish_to: https://dart.cloudsmith.io/fine-designs/flutter_utilities/
publish_to: none
repository: https://github.com/pattobrien/sidecar/

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  # analyzer: ^4.7.0
  # collection: ^1.16.0
  # path: ^1.8.0
  sidecar_package_utilities:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar_package_utilities/

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
