name: sidecar_package_utilities
description: >
  Type checkers and other utilities for creating Sidecar rule packages.
version: 0.1.0-dev.6
repository: https://www.github.com/pattobrien/sidecar
homepage: https://www.github.com/pattobrien/sidecar
issue_tracker: https://github.com/pattobrien/sidecar/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^4.1.0
  meta: ^1.7.0
  path: ^1.8.1
  source_span: ^1.8.0
  yaml: ^3.1.1
