name: sidecar_package_utilities
description: Utilities for creating sidecar packages.
version: 0.1.0-dev.2
repository: https://www.github.com/pattobrien/sidecar
homepage: https://www.github.com/pattobrien/sidecar

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^4.1.0
  path: ^1.8.2
  source_span: ^1.8.0
  yaml: ^3.1.1
