name: sidecar_package_utilities
description: A starting point for Dart libraries or applications.
version: 0.1.5
publish_to: https://dart.cloudsmith.io/fine-designs/sidecar_package_utilities/

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^4.0.0
  source_span: ^1.8.0
