name: sidecar
description: An analyzer tool that provides more control over your IDE and developer experience.
version: 0.1.0-dev.14
repository: https://github.com/pattobrien/sidecar/
homepage: https://github.com/pattobrien/sidecar/
issue_tracker: https://github.com/pattobrien/sidecar/issues

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ^4.2.0
  analyzer_plugin: ^0.11.1
  args: ^2.3.1
  characters: ^1.2.0
  checked_yaml: ^2.0.1
  cli_util: ^0.3.5
  collection: ^1.16.0
  dart_style: ^2.2.3
  file: ^6.1.4
  freezed_annotation: ^2.1.0 # non-dart official package
  glob: ^2.1.0
  hotreloader: ^3.0.5 # non-dart official package
  json_annotation: ^4.6.0
  logging: ^1.1.0
  meta: ^1.7.0
  package_config: ^2.1.0
  path: ^1.8.1
  pub_semver: ^2.1.1
  pubspec_parse: ^1.2.1
  recase: ^4.0.0 # non-dart official package
  riverpod: ^2.0.0 # non-dart official package
  sidecar_annotations: ^0.1.0-dev.1
  source_span: ^1.8.0
  uuid: ^3.0.6 # non-dart official package
  watcher: ^1.0.2
  yaml: ^3.1.1

dev_dependencies:
  analysis_server_lib: ^0.2.4
  benchmark_harness: ^2.2.0
  build_runner: ^2.2.0
  freezed: ^2.1.0
  intl_lints: ^0.1.0-dev.6
  json_serializable: ^6.3.1
  mockito: ^5.3.2
  riverpod_generator: ^1.0.0
  test: ^1.16.0

# dependency_overrides:
#   analyzer_plugin: 0.10.0

executables:
  sidecar: sidecar_cli
