name: sidecar
description: Core package for sidecar ecosystem to be built from.
version: 0.1.6
publish_to: https://dart.cloudsmith.io/fine-designs/sidecar/
repository: https://github.com/pattobrien/sidecar/

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  analyzer_plugin: ^0.11.1
  checked_yaml: ^2.0.1
  cli_util: ^0.3.5
  collection: ^1.16.0
  freezed_annotation: ^2.1.0
  glob: ^2.1.0
  json_annotation: ^4.6.0
  meta: ^1.7.0
  path: ^1.8.1
  pubspec: ^2.3.0
  pubspec_lock_parse: ^2.1.0
  pubspec_parse: ^1.2.1
  recase: ^4.0.0
  riverpod: ^1.0.3+1
  source_span: ^1.8.0
  yaml: ^3.1.1
  yaml_modify: ^1.0.1

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  lints: ^2.0.0
  test: ^1.16.0
