name: sidecar
description: Core package for sidecar ecosystem to be built from.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^4.5.0
  analyzer_plugin: ^0.11.1
  checked_yaml: ^2.0.1
  cli_util: ^0.3.5
  collection: ^1.16.0
  glob: ^2.1.0
  json_annotation: ^4.6.0
  meta: ^1.7.0
  path: ^1.8.1
  recase: ^4.0.0
  riverpod: ^2.0.0-dev.9
  source_span: ^1.8.0
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  lints: ^2.0.0
  test: ^1.16.0
