name: flutter_lints
description: A starting point for Dart libraries or applications.
version: 0.1.22
publish_to: none
# publish_to: https://micropub-3qduh.ondigitalocean.app/
repository: https://github.com/pattobrien/sidecar/tree/master/repositories/flutter_lints

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  code_builder: ^4.2.0
  collection: ^1.16.0
  # flutter_utilities:
  #   hosted: https://dart.cloudsmith.io/fine-designs/flutter_utilities/
  #   version: ^0.1.9
  flutter_analyzer_utils: ^0.2.0-dev.4
  linter: ^1.28.0
  path: ^1.8.0
  # sidecar:
  #   hosted: https://dart.cloudsmith.io/fine-designs/sidecar/
  #   version: ^0.1.20-dev.3
  sidecar:
    path: /Users/pattobrien/Development/sidecar/packages/sidecar/
  source_span: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

# dependency_overrides:
# flutter_utilities:
#   path: /Users/pattobrien/Development/sidecar/repositories/utilities/flutter_utilities/

micropub: sidecar

sidecar:
  lints:
    use_full_hex_values_for_flutter_colors:
    use_key_in_widget_constructors:
