name: flutter_lints
description: A starting point for Dart libraries or applications.
version: 0.1.0
publish_to: https://micropub-3qduh.ondigitalocean.app/

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  code_builder: ^4.2.0
  collection: ^1.16.0
  flutter_utilities:
    hosted: https://dart.cloudsmith.io/fine-designs/flutter_utilities/
    version: ^0.1.1
  path: ^1.8.0
  sidecar:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar/
    version: ^0.1.6
  source_span: ^1.9.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

# dependency_overrides:
#   sidecar:
#     path: /Users/pattobrien/Development/sidecar/packages/sidecar

micropub: sidecar
sidecar:
  edits:
    use_full_hex_values_for_flutter_colors:
      class: UseFullHexValuesForFlutterColors
      import: flutter_lints/flutter_lints.dart
    use_key_in_widget_constructors:
      class: UseKeyInWidgetConstructors
      import: flutter_lints/flutter_lints.dart
