name: auto_route_lints
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  collection: ^1.16.0
  path: ^1.8.0
  sidecar:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar/
    version: ^0.1.0-dev.18
  source_span: ^1.9.1
  flutter_utilities:
    hosted: https://dart.cloudsmith.io/fine-designs/flutter_utilities/
    version: ^0.1.0
  auto_route_utilities:
    path: ../utilities/auto_route_utilities/

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

micropub: sidecar
sidecar:
  edits:
    create_new_page_widget:
      class: CreateNewPageWidget
      import: auto_route_lints/auto_route_lints.dart
# dependency_overrides:
#   sidecar:
#     path: /Users/pattobrien/Development/sidecar/packages/sidecar
