name: auto_route_lints
description: A starting point for Dart libraries or applications.
version: 0.1.2
publish_to: https://micropub-3qduh.ondigitalocean.app/
repository: https://github.com/pattobrien/sidecar/tree/master/repositories/auto_route_lints/

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  auto_route_utilities:
    hosted: https://dart.cloudsmith.io/fine-designs/auto_route_utilities/
    version: ^0.1.0
  code_builder: ^4.2.0
  collection: ^1.16.0
  flutter_utilities:
    hosted: https://dart.cloudsmith.io/fine-designs/flutter_utilities/
    version: ^0.1.1
  path: ^1.8.0
  sidecar:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar/
    version: ^0.1.8-dev.2
  source_span: ^1.9.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

micropub: sidecar
sidecar:
  edits:
    create_new_page_widget:
      class: CreateNewPageWidget
      import: auto_route_lints/auto_route_lints.dart
