name: l10n_lints
description: A starting point for Dart libraries or applications.
version: 0.1.0-dev.1
publish_to: https://micropub-3qduh.ondigitalocean.app/

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  collection: ^1.16.0
  path: ^1.8.0
  sidecar:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar/
    version: ^0.1.0-dev.18
  source_span: ^1.9.1
  flutter_utilities:
    hosted: https://dart.cloudsmith.io/fine-designs/flutter_utilities/
    version: ^0.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

micropub: sidecar

sidecar:
  lints:
    avoid_string_literals:
      class: AvoidStringLiterals
      import: l10n_lints/l10n_lints.dart
