name: riverpod_utilities
description: A starting point for Dart libraries or applications.
version: 0.1.2
publish_to: https://dart.cloudsmith.io/fine-designs/riverpod_utilities/

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer_plugin: ^0.11.1
  path: ^1.8.0
  sidecar:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar/
    version: ^0.1.8-dev.1

# dependency_overrides:
#   sidecar:
#     path: ../../../packages/sidecar/

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
