name: pubspec_utilities
description: A starting point for Dart libraries or applications.
version: 0.1.0
publish_to: https://dart.cloudsmith.io/fine-designs/pubspec_utilities/

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  path: ^1.8.0
  pubspec: ^2.3.0
  pubspec_parse: ^1.2.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
