name: benchmark
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  sidecar_analyzer_plugin:
    path: .sidecar/sidecar_analyzer_plugin

flutter:
  uses-material-design: true

dependency_overrides:
  #   #   # sidecar:
  #   #   #   path: /Users/pattobrien/Development/sidecar/packages/sidecar/
  sidecar_analyzer_plugin_core:
    path: /Users/pattobrien/Development/sidecar/packages/sidecar_analyzer_plugin_core/
