name: riverpod_lints
description: A starting point for Dart libraries or applications.
version: 0.1.8
publish_to: https://micropub-3qduh.ondigitalocean.app/
repository: https://github.com/pattobrien/sidecar/tree/master/repositories/riverpod_lints/

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  analyzer_plugin: ^0.11.1
  collection: ^1.16.0
  path: ^1.8.0
  riverpod_utilities:
    hosted: https://dart.cloudsmith.io/fine-designs/riverpod_utilities/
    version: ^0.1.1
  sidecar:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar/
    version: ^0.1.8-dev.7

dev_dependencies:
  lints: ^2.0.0

micropub: sidecar

sidecar:
  lints:
    prefer_consumer_widget:
      class: PreferConsumerWidget
      import: riverpod_lints/riverpod_lints.dart
  #   avoid_read_in_build_methods:
  #     class: AvoidReadInBuildMethods
  #     import: riverpod_lints/riverpod_lints.dart
  edits:
    create_text_edit_controller_provider:
      class: CreateTextEditControllerProvider
      import: riverpod_lints/riverpod_lints.dart
