name: riverpod_lints
description: A starting point for Dart libraries or applications.
version: 0.1.0-dev.1
publish_to: https://micropub-3qduh.ondigitalocean.app/

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  collection: ^1.16.0
  path: ^1.8.0
  riverpod_utilities:
    hosted: https://dart.cloudsmith.io/fine-designs/riverpod_utilities/
    version: ^0.1.0
  sidecar:
    hosted:
      url: https://dart.cloudsmith.io/fine-designs/sidecar/
      name: sidecar
    version: ^0.1.0-dev.16

dev_dependencies:
  lints: ^2.0.0

dependency_overrides:
  sidecar:
    path: /Users/pattobrien/Development/sidecar/packages/sidecar/

sidecar:
  lints:
    prefer_consumer_widget:
      class: PreferConsumerWidget
      import: riverpod_lints/riverpod_lints.dart
    avoid_read_in_build_methods:
      class: AvoidReadInBuildMethods
      import: riverpod_lints/riverpod_lints.dart
