name: design_system_annotations
description: A starting point for Dart libraries or applications.
version: 0.1.0
publish_to: https://micropub-3qduh.ondigitalocean.app/
repository: https://github.com/pattobrien/sidecar/tree/master/repositories/design_system_annotations

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  sidecar_annotations:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar_annotations/
    version: ^0.1.18

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

micropub: sidecar

sidecar:
  lints:
