name: workspace_analyzer_plugin_loader
description: This pubspec determines the version of the analyzer plugin to load.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  sidecar_analyzer_plugin:
    path: /Users/pattobrien/Development/sidecar/packages/sidecar_analyzer_plugin
