includes:
  - "lib/**.dart"
lints:
  design_system_lints:
    rules:
      avoid_sized_box_height_width_literals:
      avoid_text_style_literal:
      avoid_border_radius_literal:
      avoid_box_shadow_literal:
      avoid_edge_insets_literal:
