name: riverpod_analyzer
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  sidecar:
    path: /Users/pattobrien/Development/sidecar/packages/sidecar

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
