name: riverpod_analyzer
description: A starting point for Dart libraries or applications.
version: 2.0.0
publish_to: https://micropub-3qduh.ondigitalocean.app/
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  riverpod: 2.0.0
  sidecar_package_utilities:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar_package_utilities/
    version: ^0.1.0

sidecar_package: riverpod

micropub: sidecar

sidecar:
  lints:
