name: sidecar_cli
description: A sample command-line application.
version: 0.1.11-dev.1
publish_to: https://dart.cloudsmith.io/fine-designs/sidecar_cli/
repository: https://github.com/pattobrien/sidecar/

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  args: ^2.3.1
  checked_yaml: ^2.0.1
  cli_util: ^0.3.5
  code_builder: ^4.2.0
  dotenv: ^4.0.1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  path: ^1.8.0
  pub_semver: ^2.1.1
  pubspec_lock_parse: ^2.1.0
  pubspec_parse: ^1.2.1
  pubspec_utilities:
    hosted: https://dart.cloudsmith.io/fine-designs/pubspec_utilities/
    version: ^0.1.0
  recase: ^4.0.0
  riverpod: ^1.0.3+1
  sidecar:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar/
    version: ^0.1.11-dev.1

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  lints: ^2.0.0

executables:
  sidecar: sidecar_cli
