name: sidecar_cli
description: A sample command-line application.
version: 0.1.0-dev.3
publish_to: https://dart.cloudsmith.io/fine-designs/sidecar_cli/
repository: https://github.com/pattobrien/sidecar/

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  args: ^2.3.1
  checked_yaml: ^2.0.1
  dotenv: ^4.0.1
  path: ^1.8.0
  pubspec_parse: ^1.2.1
  recase: ^4.0.0
  riverpod: ^2.0.0-dev.9
  sidecar:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar/
    version: 0.1.0-dev.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  sidecar: sidecar_cli
