name: sidecar_cli
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  args: ^2.3.1
  checked_yaml: ^2.0.1
  path: ^1.8.0
  pubspec_parse: ^1.2.1
  recase: ^4.0.0
  riverpod: ^2.0.0-dev.9
  sidecar:
    git:
      url: git@github.com:pattobrien/sidecar.git
      path: packages/sidecar
      ref: master

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  sidecar: sidecar_cli
