name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  analyzer: ^4.2.0
  path: ^1.8.0
  sidecar: ^0.1.0-dev.16

dev_dependencies:
  lints: ^2.0.0
  sidecar_lints:
    path: /Users/pattobrien/Development/sidecar/packages/sidecar_lints/
