name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  analyzer: ^4.2.0
  sidecar: ^0.1.0-dev.19

dev_dependencies:
  lints: ^2.0.0
  sidecar_lints: ^0.1.0-dev.2

sidecar:
  lints:
    - example_lint
    - example_lint_with_function_block_with_return

dependency_overrides:
  sidecar_lints:
    path: /Users/pattobrien/Development/sidecar/packages/sidecar_lints/
  sidecar:
    path: /Users/pattobrien/Development/sidecar/packages/sidecar/
