name: sidecar_analyzer_plugin
description: Analyzer plugin for the sidecar ecosystem.
version: 0.1.15-dev.2
publish_to: https://dart.cloudsmith.io/fine-designs/sidecar_analyzer_plugin/
repository: https://github.com/pattobrien/sidecar/

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  sidecar:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar/
    version: ^0.1.15-dev.2
  sidecar_analyzer_plugin_core:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar_analyzer_plugin_core/
    version: ^0.1.15-dev.2
  # l10n_lints:
  #   path: /Users/pattobrien/Development/sidecar/repositories/l10n_lints/ ## REMOVE THIS TOO
dev_dependencies:
  test: ^1.21.4
  #
  # dependency_overrides:
  #   l10n_lints:
  #     path: /Users/pattobrien/Development/sidecar/repositories/l10n_lints/
  # sidecar:
  #   path: /Users/pattobrien/Development/sidecar/packages/sidecar/
  # sidecar_analyzer_plugin_core:
  #   path: /Users/pattobrien/Development/sidecar/packages/sidecar_analyzer_plugin_core/
