name: sidecar_analyzer_plugin
description: Analyzer plugin for the sidecar ecosystem.
version: 0.1.7
publish_to: https://dart.cloudsmith.io/fine-designs/sidecar_analyzer_plugin/
repository: https://github.com/pattobrien/sidecar/

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  analyzer_plugin: ^0.11.1
  riverpod: ^1.0.3+1
  sidecar:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar/
    version: ^0.1.7
  sidecar_analyzer_plugin_core:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar_analyzer_plugin_core/
    version: ^0.1.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
