name: bloc_analyzer_utils
description: A sample command-line application.
version: 0.1.0-dev.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  sidecar_package_utilities: ^0.1.0-dev.1
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

sidecar_package: bloc
