include: package:lints/recommended.yaml

linter:
  rules:
    - camel_case_types

analyzer:
  plugins:
    - sidecar_analyzer_plugin

sidecar_analyzer_plugin:
  includes:
    - "bin/**"
    - "lib/**"
    - ".sidecar/**"
  rules:
    - id: riverpod_prefer_consumer_widget
#
# proposed_rule_format:
#   - riverpod:avoid_string_literals
#   - riverpod:avoid_stateless_widget
# or:
#   - dart/avoid_stateless_widget
#   - flutter/use_full_hex_values_for_flutter_colors
#   - riverpod/avoid_stateless_widget
