include: package:lints/recommended.yaml

linter:
  rules:
    - camel_case_types

analyzer:
  plugins:
    - sidecar_analyzer_plugin

sidecar_analyzer_plugin:
  includes:
    - "bin/**"
    - "lib/**"
    - ".sidecar/**"
  rules:
    - id: riverpod_prefer_consumer_widget
    - id: l10n_avoid_string_literals
