include: package:lints/recommended.yaml

linter:
  rules:
    camel_case_types: true
    prefer_relative_imports: true
    always_declare_return_types: false
    # - use_key_in_widget_constructors
    # - use_full_hex_values_for_flutter_colors
# analyzer:
#   plugins:
#     - sidecar
