include: package:lints/recommended.yaml

linter:
  rules:
    - camel_case_types
    - prefer_relative_imports

analyzer:
  plugins:
    - sidecar_analyzer_plugin

sidecar:
  includes:
    - "bin/**"
    - "lib/**"
    # - ".sidecar/**"
  lints:
    riverpod_lints:
      prefer_consumer_widget:
        enabled: true
        configuration:
          aaaaa: 11111
    l10n_lints:
      avoid_string_literals:
        enabled: true
        configuration:
          prefix: AppLocalizations.of(context)

  edits:
    auto_route_lints:
      create_new_page_widget:
        enabled: true
        configuration:
          route_path: lib/routes/routes.dart
    riverpod_lints:
      create_text_edit_controller_provider:
        enabled: true
        configuration:
          nested_value:
            - 123
  #         something:
  #           abc: 123
