include: package:lints/recommended.yaml

linter:
  rules:
    - camel_case_types
    - prefer_relative_imports

analyzer:
  plugins:
    - sidecar_analyzer_plugin

sidecar:
  includes:
    - "bin/**"
    - "lib/**"
    # - ".sidecar/**"
  lints:
    # flutter_lints:
    #   use_full_hex_values_for_flutter_colors:
    #   use_key_in_widget_constructors:
    # riverpod_lints:
    #   prefer_consumer_widget:
    #     configuration:
    #       some_property: abc

    # l10n_lints:
    #   avoid_string_literals:
    #     configuration:
    #       prefix: "AppLocalizations.of(context)"

    project_lints:
      avoid_icon_literal:
        severity: error
      avoid_sized_box_height_width_literals:
    # design_system_lints:
    #   avoid_color_literal:
    #   avoid_sized_box_height_width_literals:
    # avoid_text_style_literal:
    # avoid_border_radius_literal:
    # avoid_box_shadow_literal:
    # avoid_edge_insets_literal:
    # project_lints:

  # edits:
  #   riverpod_lints:
  #     create_text_edit_controller_provider:
  #   sidecar_lints:
  #     output_ast_node_tree:
