include: package:lints/recommended.yaml

linter:
  rules:
    - camel_case_types
    - prefer_relative_imports
    # - use_full_hex_values_for_flutter_colors

analyzer:
  plugins:
    - sidecar_analyzer_plugin

sidecar:
  includes:
    - "bin/**"
    - "lib/**"
    # - ".sidecar/**"
  lints:
    flutter_lints:
      use_full_hex_values_for_flutter_colors:
      use_key_in_widget_constructors:

    l10n_lints:
      avoid_string_literals:
        configuration:
          prefix: "AppLocalizations.of(context)"

    riverpod_lints:
      prefer_consumer_widget:
        configuration:
          some_property: abc
    # various_lints:
    #   avoid_flutter_in_application_layer:

  edits:
    riverpod_lints:
      create_text_edit_controller_provider:
    sidecar_lints:
      output_ast_node_tree:
    # auto_route_lints:
    #   create_new_page_widget:
    #     configuration:
    #       route_path: lib/routes/routes.dart
