include: package:lints/recommended.yaml

linter:
  rules:
    - camel_case_types

analyzer:
  plugins:
    - sidecar_analyzer_plugin

example_plugin:
  lints:
    riverpod:
      prefer_consumer_widget:
    l10n:
      - avoid_string_literals
  edits:
    riverpod:
      create_text_edit_controller_provider: null
      prefer_consumer_widget: true

sidecar:
  includes:
    - "bin/**"
    - "lib/**"
    # - ".sidecar/**"
  lints:
    riverpod_prefer_consumer_widget:
    l10n_avoid_string_literals:
      abc: hi
  edits:
    create_text_edit_controller_provider:
      enabled: true
      another: abc123
      nested:
        - 123
