include: package:lints/recommended.yaml

# auto_route_lints:
#   create_new_page_widget:
#     enabled: true
#     configuration:
#       route_path: lib/routes/routes.dart
# riverpod_lints:
#   create_text_edit_controller_provider:
#     enabled: true
#     configuration:
#       nested_value:
# - 123
#         something:
#           abc: 123

linter:
  rules:
    - camel_case_types
    - prefer_relative_imports
    # - use_full_hex_values_for_flutter_colors

analyzer:
  plugins:
    - sidecar_analyzer_plugin

sidecar:
  includes:
    - "bin/**"
    - "lib/**"
    # - ".sidecar/**"
  lints:
    flutter_lints:
      use_full_hex_values_for_flutter_colors:
        enabled: true
        configuration:
          abc: 123
    l10n_lints:
      avoid_string_literals:
        # enabled: true
        # configuration:
        #   prefix: AppLocalizations.of(context)
    riverpod_lints:
      prefer_consumer_widget:
        enabled: true
        configuration:
          aaaaa: 11111

  edits:
    riverpod_lints:
      create_text_edit_controller_provider:
        enabled: true
        configuration:
          nested_value: 123
