name: my_analyzed_codebase
description: An example of a project analyzed by Sidecar.
version: 1.0.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.9
  path: ^1.8.0

dev_dependencies:
  sidecar_analyzer_plugin_starter:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar_analyzer_plugin_starter/
    version: ^0.1.0-dev.7 # version constraint can be explicitly specified

  lints: ^2.0.0
  test: ^1.16.0

flutter:
  uses-material-design: true

dependency_overrides:
  sidecar_analyzer_plugin_starter:
    path: .sidecar/sidecar_analyzer_plugin_starter/
