name: my_analyzed_codebase
description: An example of a project analyzed by Sidecar.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  auto_route: ^5.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  path: ^1.8.0
  intl: ^0.17.0
  # design_system_annotations:
  #   hosted: https://micropub-3qduh.ondigitalocean.app/
  # sidecar_annotations:
  #   hosted: https://dart.cloudsmith.io/fine-designs/sidecar_annotations/
  #   version: ^0.1.18

dev_dependencies:
  auto_route_generator: ^5.0.2
  lints: ^2.0.0
  sidecar_analyzer_plugin_core:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar_analyzer_plugin_core/
    version: ^0.1.21-dev.4
    # path: /Users/pattobrien/Development/sidecar/packages/sidecar_analyzer_plugin_core/
  test: ^1.16.0

  # project_lints:
  #   path: tool/project_lints
  # sidecar_analyzer_plugin:
  #   path: .sidecar/sidecar_analyzer_plugin/

flutter:
  uses-material-design: true
  generate: true
