name: my_analyzed_codebase
description: An example of a project analyzed by Sidecar.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  auto_route: ^5.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  path: ^1.8.0
  intl: ^0.17.0
  my_backend_client:
    path: packages/my_backend_client/

dev_dependencies:
  auto_route_generator: ^5.0.2
  dart_lints: ^0.1.0-dev.2
  design_system_lints: ^0.1.0-dev.8
  intl_lints: ^0.1.0-dev.7
  json_annotation: 4.6.0
  lints: ^2.0.0
  sidecar: 0.1.0-dev.16
  # sidecar_lints:
  #   path: ../../packages/sidecar_lints/
  test: ^1.16.0

flutter:
  uses-material-design: true
  generate: true
