name: my_analyzed_codebase
description: An example of a project analyzed by Sidecar.
version: 1.0.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  auto_route: ^5.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.3+1
  path: ^1.8.0

dev_dependencies:
  auto_route_generator: ^5.0.2
  intl: ^0.17.0
  lints: ^2.0.0
  sidecar_analyzer_plugin: 
    hosted:
      url: https://dart.cloudsmith.io/fine-designs/sidecar_analyzer_plugin/
      name: sidecar_analyzer_plugin
    version: ^0.1.6
  test: ^1.16.0

dependency_overrides:
  sidecar_analyzer_plugin:
    path: /Users/pattobrien/Development/sidecar/examples/my_analyzed_codebase/.sidecar/sidecar_analyzer_plugin/
  # sidecar:
  #   path: /Users/pattobrien/Development/sidecar/packages/sidecar/
flutter:
  uses-material-design: true
  generate: true
