name: my_analyzed_codebase
description: An example of a project analyzed by Sidecar.
version: 1.0.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.9
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  sidecar_analyzer_plugin: 
    hosted:
      url: https://dart.cloudsmith.io/fine-designs/sidecar_analyzer_plugin/
      name: sidecar_analyzer_plugin
    version: ^0.1.0-dev.14
  test: ^1.16.0

dependency_overrides:
  sidecar_analyzer_plugin:
    path: /Users/pattobrien/Development/sidecar/examples/my_analyzed_codebase/.sidecar/sidecar_analyzer_plugin/

flutter:
  uses-material-design: true
