name: my_analyzed_codebase
description: An example of a project analyzed by Sidecar.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  auto_route: ^5.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  path: ^1.8.0
  intl: ^0.17.0

dev_dependencies:
  auto_route_generator: ^5.0.2
  lints: ^2.0.0
  design_system_lints:
    path: /Users/pattobrien/Development/sidecar/repositories/design_system_lints/
  sidecar_analyzer_plugin_core:
    path: /Users/pattobrien/Development/sidecar/packages/sidecar_analyzer_plugin_core/
    # hosted: https://dart.cloudsmith.io/fine-designs/sidecar_analyzer_plugin_core/
    # version: 0.1.21-dev.11
  test: ^1.16.0

flutter:
  uses-material-design: true
  generate: true
