name: my_analyzed_codebase
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.9
  path: ^1.8.0

dev_dependencies:
  sidecar_analyzer_plugin:
    path: .sidecar/sidecar_analyzer_plugin # code-generated
  lints: ^2.0.0
  test: ^1.16.0

flutter:
  uses-material-design: true
