name: my_analyzed_codebase
description: An example of a project analyzed by Sidecar.
version: 1.0.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.9
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  sidecar_analyzer_plugin:
    path: .sidecar/sidecar_analyzer_plugin
  test: ^1.16.0

flutter:
  uses-material-design: true
