name: my_analyzed_codebase
description: An example of a project analyzed by Sidecar.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  auto_route: ^5.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.3+1
  path: ^1.8.0
  intl: ^0.17.0

dev_dependencies:
  auto_route_generator: ^5.0.2
  lints: ^2.0.0
  test: ^1.16.0
  project_lints:
    path: tool/project_lints
  sidecar_analyzer_plugin:
    path: .sidecar/sidecar_analyzer_plugin
  # sidecar_analyzer_plugin:
  #   path: .sidecar/sidecar_analyzer_plugin/

flutter:
  uses-material-design: true
  generate: true
# dependency_overrides:
# sidecar:
#   path: /Users/pattobrien/Development/sidecar/packages/sidecar/
#   sidecar_analyzer_plugin_core:
#     path: /Users/pattobrien/Development/sidecar/packages/sidecar_analyzer_plugin_core/
