name: hello_world_rules
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  sidecar: ^0.1.0-dev.18

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

sidecar:
  lints:
    - hello_world
