name: sidecar_lints
description: Lints to assist developers with creating their own Sidecar packages.
version: 0.1.0-dev.1
repository: https://github.com/pattobrien/sidecar/
homepage: https://github.com/pattobrien/sidecar/
issue_tracker: https://github.com/pattobrien/sidecar/issues

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  analyzer_plugin: ^0.11.1
  sidecar: ^0.1.0-dev.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

sidecar:
  assists:
    - output_ast_node_tree
    - output_source_span
