name: website
description: >
  Sidecar website code snippets.
repository: https://github.com/pattobrien/sidecar/
homepage: https://github.com/pattobrien/sidecar/
issue_tracker: https://github.com/pattobrien/sidecar/issues
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ^5.0.0
  freezed_annotation: ^2.1.0 # non-dart official package
  glob: ^2.1.0
  json_annotation: ^4.6.0
  meta: ^1.7.0
  path: ^1.8.1
  pub_semver: ^2.1.1
  sidecar:
    path: ../../packages/sidecar/
  # sidecar_annotations:
  #   path: ../../packages/sidecar_annotations/
  # sidecar_package_utilities:
  #   path: ../../packages/sidecar_package_utilities/
  source_span: ^1.8.0
  test: ^1.16.0

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0
  json_serializable: ^6.3.1
