name: various_lints
description: A starting point for Dart libraries or applications.
version: 0.1.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  code_builder: ^4.2.0
  collection: ^1.16.0
  flutter_utilities:
    hosted: https://dart.cloudsmith.io/fine-designs/flutter_utilities/
    version: ^0.1.9
  path: ^1.8.0
  sidecar:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar/
    version: ^0.1.20-dev.3
  source_span: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

micropub: sidecar

sidecar:
  lints:
    avoid_flutter_in_application_layer:
      class: AvoidFlutterInApplicationLayer
      import: various_lints/various_lints.dart
