name: sidecar_analyzer_plugin_starter
description: A sample command-line application.
version: 0.1.0-dev.7
publish_to: https://dart.cloudsmith.io/fine-designs/sidecar_analyzer_plugin_starter/
repository: https://github.com/pattobrien/sidecar/

# TODO: could we instead upload the package in the tools/analyzer_plugin?

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  riverpod: ^2.0.0-dev.9
  sidecar:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar/
    version: ^0.1.0-dev.7
  sidecar_analyzer_plugin:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar_analyzer_plugin/
    version: ^0.1.0-dev.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
# dependency_overrides:
#   sidecar_analyzer_plugin:
#     path: ../sidecar_analyzer_plugin/
