name: sidecar_analyzer_plugin_starter_loader
description: This pubspec determines the version of the analyzer plugin to load.
version: 0.1.0-dev.7
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  sidecar_analyzer_plugin_starter:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar_analyzer_plugin_starter/
    version: ^0.1.0-dev.7
