name: sidecar_generator
description: A starting point for Dart libraries or applications.
version: 0.1.0-dev.1
publish_to: none
# homepage: https://www.example.com
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  analyzer_plugin: ^0.11.1
  build: ^2.3.1
  code_builder: ^4.3.0
  collection: ^1.16.0
  dart_style: ^2.2.4
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  path: ^1.8.0
  sidecar:
    path: /Users/pattobrien/Development/sidecar/packages/sidecar/
  source_gen: ^1.2.6
  source_span: ^1.8.2
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.3.0
  freezed: ^2.2.0
  json_serializable: ^6.5.1
  lints: ^2.0.0
  test: ^1.16.0
