name: design_system_lints
description: A starting point for Dart libraries or applications.
version: 0.1.12
publish_to: https://micropub-3qduh.ondigitalocean.app/
repository: https://github.com/pattobrien/sidecar/tree/master/repositories/design_system_lints

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  code_builder: ^4.2.0
  collection: ^1.16.0
  flutter_utilities:
    hosted: https://dart.cloudsmith.io/fine-designs/flutter_utilities/
    version: ^0.1.10
  path: ^1.8.0
  sidecar:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar/
    version: ^0.1.21-dev.2
  source_span: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

micropub: sidecar

sidecar:
  lints:
    - avoid_color_literal
    - avoid_edge_insets_literal
    - avoid_icon_literal
    - avoid_box_shadow_literal
    - avoid_text_style_literal
    - avoid_border_radius_literal
    - avoid_sized_box_height_width_literals
