name: design_system_lints
description: A collection of lints and code edits to enforce UI standards within a codebase.
version: 0.1.0-dev.2
repository: https://github.com/pattobrien/sidecar/tree/master/repositories/design_system_lints
homepage: https://github.com/pattobrien/sidecar/tree/master/repositories/design_system_lints

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ^4.2.0
  flutter_analyzer_utils: ^0.2.0-dev.4
  sidecar: ^0.1.0-dev.2

dev_dependencies:
  build_runner: ^2.3.0
  lints: ^2.0.0
  test: ^1.16.0

sidecar:
  lints:
    # - avoid_color_literal
    - avoid_edge_insets_literal
    - avoid_icon_literal
    - avoid_box_shadow_literal
    - avoid_text_style_literal
    - avoid_border_radius_literal
    - avoid_sized_box_height_width_literals
