name: design_system_lints
description: A starting point for Dart libraries or applications.
version: 0.1.12
# publish_to: https://micropub-3qduh.ondigitalocean.app/
publish_to: none
repository: https://github.com/pattobrien/sidecar/tree/master/repositories/design_system_lints

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  code_builder: ^4.2.0
  collection: ^1.16.0
  flutter_utilities:
    hosted: https://dart.cloudsmith.io/fine-designs/flutter_utilities/
    version: ^0.1.12
  freezed_annotation: ^2.2.0
  sidecar:
    path: /Users/pattobrien/Development/sidecar/packages/sidecar
  sidecar_package_utilities:
    path: /Users/pattobrien/Development/sidecar/packages/sidecar_package_utilities
  source_span: ^1.8.2

dev_dependencies:
  build_runner: ^2.3.0
  freezed: ^2.2.0
  lints: ^2.0.0
  sidecar_generator:
    path: /Users/pattobrien/Development/sidecar/packages/sidecar_generator/
  test: ^1.16.0

dependency_overrides:
  flutter_utilities:
    path: /Users/pattobrien/Development/sidecar/repositories/utilities/flutter_utilities/

micropub: sidecar

sidecar:
  lints:
    - avoid_color_literal
    - avoid_edge_insets_literal
    - avoid_icon_literal
    - avoid_box_shadow_literal
    - avoid_text_style_literal
    - avoid_border_radius_literal
    - avoid_sized_box_height_width_literals
