name: lint_repository
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^4.6.0
  collection: ^1.16.0
  path: ^1.8.0
  sidecar:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar/
    version: ^0.1.0-dev.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
