name: benchmarks
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  riverpod: ^2.0.2
  sidecar:
    path: ../packages/sidecar
  design_system_lints:
    path: ../repositories/design_system_lints/
dependency_overrides:
  sidecar:
    path: ../packages/sidecar
  design_system_lints:
    path: ../repositories/design_system_lints/
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
