name: bloc_analyzer
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  sidecar_package_utilities:
    path: ../../packages/sidecar_package_utilities
  bloc: ^1.0.0
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

sidecar_package: bloc
