name: Build

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - master
      - "refactor/**"
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ${{ matrix.runners }}

    defaults:
      run:
        working-directory: ${{ matrix.package_path }}

    strategy:
      matrix:
        runners:
          # - self-hosted
          # - ubuntu-latest
          - windows-latest
        flutter-version:
          - "3.0.5"
          # - "3.3.9"
        package_path:
          - packages/sidecar
        # channel:
        #   - stable

    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 2

      - uses: subosito/flutter-action@v2.7.1
        with:
          # channel: ${{ matrix.channel }}
          channel: stable
          flutter-version: ${{ matrix.flutter-version }}
          cache: true

      - name: Add pub cache bin to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Add pub cache to PATH
        run: echo "PUB_CACHE="$HOME/.pub-cache"" >> $GITHUB_ENV

      - name: Install dependencies
        run: flutter pub get

      - name: install coverage
        run: dart pub global activate coverage

      - name: Run tests
        run: dart test --coverage="coverage"

      - name: Format code coverage
        run: dart pub global run coverage:format_coverage --packages=.dart_tool/package_config.json --report-on=lib --lcov -o ./coverage/lcov.info -i ./coverage

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3.1.1
