name: Build

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - master
      - "refactor/**"
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ matrix.package_path }}

    strategy:
      matrix:
        channel:
          - stable
        package_path:
          # - examples/my_analyzed_codebase
          - packages/sidecar

    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 2
      - uses: subosito/flutter-action@v2.7.1
        with:
          channel: ${{ matrix.channel }}
      - name: Add pub cache bin to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
      - name: Add pub cache to PATH
        run: echo "PUB_CACHE="$HOME/.pub-cache"" >> $GITHUB_ENV
      - name: Install dependencies
        run: flutter pub get

      # - name: Check format
      #   run: flutter format --set-exit-if-changed .
      #   if: matrix.package_path != 'website'

      # - name: Analyze
      #   run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3.1.1
